version: "3"
services:
  raspberrypi-7514dd1cfcaa49ceb338ea1d935db8bb-base:
    image: raspberrypi-7514dd1cfcaa49ceb338ea1d935db8bb-base
    build:
      context: ..
      dockerfile: Dockerfile
  raspberrypi-7514dd1cfcaa49ceb338ea1d935db8bb-devcontainer:
    depends_on: [ "raspberrypi-7514dd1cfcaa49ceb338ea1d935db8bb-base" ]
    image: raspberrypi-7514dd1cfcaa49ceb338ea1d935db8bb-devcontainer
    privileged: true
    network_mode: host
    env_file:
     - .env
    build:
      context: ..
      dockerfile: .devcontainer/dev.Dockerfile
    volumes:
      - /tmp/raspberrypi-7514dd1cfcaa49ceb338ea1d935db8bb:/workspace
    command: /bin/sh -c "while sleep 1000; do :; done"