#! /bin/bash

# This hook runs AFTER all files except post-deactivate and post-deactivate.env are deleted from the
# active devcontainer folder. You can't do much here other than a second check to ensure pre-deactivate
# was successful (I think)

echo "post-deactivate hook for template: $DEVCONTAINER_NAME running in $PWD"